// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiqayurtpisijoyntxls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcWF5dXJ0cGlzaWpveW50eGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Mjk0MTcsImV4cCI6MjA2MTIwNTQxN30.wckrE5V434bNHQeL5hbj-FAmUGdUeq89wmYUr8d7_9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);